### ISSUE TITLE
remove the jQuery dependecy

### ISSUE THREAD

**Issue by oriSomething** [eshirazi/ember-resizable-table#2]
jQuery will likely be deprecated / won't ship on Ember 3

#### EDIT

we also need to remove the inject styles mixin. We can use attribute bindings for that

**Comment by eshirazi** [comment]
@oriSomething, thanks for the good work man :)
I merged, and added a small change to use the formatStyle function instead of rewriting it:
https://github.com/eshirazi/ember-resizable-table/commit/e1030f75b47bd3645995adad4e58d8f97f31b3c7

**Comment by oriSomething** [comment]
Hey, you've made double use of `htmlSafe`. Both in `formatStyle` utility and both in `{{resizable-table-cell}}` component

**Comment by eshirazi** [comment]
Right, thanks! Fixed:
https://github.com/eshirazi/ember-resizable-table/commit/5f0672948ad7ef3df4d5bf1fc02c3875fc11b473
